pipeline {
    agent {
        label 'linux && swarm'
    } 

    stages {
        stage('Linting') {
          steps {
            sh "flake8 app/site.py"
          }
        }
        stage('Build') {
        steps {
            sh "docker build -t classweb:${BUILD_NUMBER} /workspace/docker-pipeline/"
            
          }
        }
        stage('Test') {
        steps {
            sh "docker run -d -p 80:8080  --name classweb1 classweb:${BUILD_NUMBER}"
            sh '''curl $(curl 169.254.169.254/latest/meta-data/local-ipv4) | grep "super"
            '''
          }
        }        
    }
    post {
    always {
      sh '''docker ps -aq --filter "name=classweb1" | grep -q . && docker container rm -f classweb1'''
    }
  }
}
